"""
File: my_drawing.py
Name: 李知穎 Anita Lee
----------------------
Title: EVA
Recreating Evangelion, one of my favorite anime, with python
"""

from campy.graphics.gobjects import GRect, GPolygon
from campy.graphics.gwindow import GWindow
from campy.graphics.gcolor import GColor
WINDOW_H = 457
WINDOW_W = 564


def main():
    """
    TODO: This program recreates the image
    """
    window = GWindow(WINDOW_W, WINDOW_H)
    # each part of the image can be obtained through different functions, the codes were generated by get_object.py
    background_color(window)
    horn(window)
    head(window)
    arm(window)
    body(window)
    words(window)


def background_color(window):
    background = GRect(window.width, window.height)
    background.filled = True
    background.fill_color = 'black'
    window.add(background)


def head(window):
    # eye1
    eye1 = GPolygon()
    eye1.add_vertex(point=(161, 217))
    eye1.add_edge(-1, -3)
    eye1.add_edge(5, -7)
    eye1.add_edge(3, 1)
    eye1.add_edge(-4, 7)
    eye1.filled = True
    eye1.fill_color = "white"
    window.add(eye1)
    # head1
    head1 = GPolygon()
    head1.add_vertex(point=(150, 191))
    head1.add_edge(0, -4)
    head1.add_edge(14, -14)
    head1.add_edge(-1, 3)
    head1.add_edge(5, -3)
    head1.add_edge(5, 3)
    head1.add_edge(-2, 14)
    head1.add_edge(6, -18)
    head1.add_edge(-10, -4)
    head1.add_edge(-7, 5)
    head1.add_edge(6, -14)
    head1.add_edge(30, -21)
    head1.add_edge(-3, 20)
    head1.add_edge(-6, 8)
    head1.add_edge(3, 14)
    head1.add_edge(-4, 6)
    head1.add_edge(-8, 4)
    head1.add_edge(-7, 13)
    head1.add_edge(-6, 2)
    head1.add_edge(-6, 7)
    head1.add_edge(0, 6)
    head1.add_edge(-3, 3)
    head1.add_edge(-6, 0)
    head1.add_edge(-2, -6)
    head1.add_edge(3, -13)
    head1.filled = True
    head1.fill_color = "white"
    window.add(head1)
    # head2
    head2 = GPolygon()
    head2.add_vertex(point=(156, 223))
    head2.add_edge(3, -4)
    head2.add_edge(4, -1)
    head2.add_edge(1, -1)
    head2.add_edge(7, 3)
    head2.add_edge(-2, 6)
    head2.add_edge(-11, 2)
    head2.add_edge(-1, 5)
    head2.add_edge(-6, 0)
    head2.add_edge(0, -3)
    head2.filled = True
    head2.fill_color = "white"
    window.add(head2)
    # head3
    head3 = GPolygon()
    head3.add_vertex(point=(158, 235))
    head3.add_edge(1, -5)
    head3.add_edge(6, 0)
    head3.add_edge(0, 4)
    head3.add_edge(-4, 5)
    head3.filled = True
    head3.fill_color = "white"
    window.add(head3)
    # head4
    head4 = GPolygon()
    head4.add_vertex(point=(172, 203))
    head4.add_edge(7, -11)
    head4.add_edge(23, -11)
    head4.add_edge(12, -28)
    head4.add_edge(-5, -11)
    head4.add_edge(-4, -2)
    head4.add_edge(6, -9)
    head4.add_edge(21, -11)
    head4.add_edge(4, 3)
    head4.add_edge(0, 19)
    head4.add_edge(-14, 7)
    head4.add_edge(-1, 14)
    head4.add_edge(-4, 4)
    head4.add_edge(1, 10)
    head4.add_edge(3, 7)
    head4.add_edge(-6, 11)
    head4.add_edge(-24, 4)
    head4.add_edge(1, -3)
    head4.add_edge(-4, 0)
    head4.add_edge(-6, 11)
    head4.add_edge(-4, -5)
    head4.filled = True
    head4.fill_color = "white"
    window.add(head4)
    # head5
    head5 = GPolygon()
    head5.add_vertex(point=(190, 201))
    head5.add_edge(-8, 16)
    head5.add_edge(2, 4)
    head5.add_edge(10, -3)
    head5.add_edge(21, -22)
    head5.add_edge(-17, 2)
    head5.filled = True
    head5.fill_color = "white"
    window.add(head5)
    # head6
    head6 = GPolygon()
    head6.add_vertex(point=(201, 179))
    head6.add_edge(8, -18)
    head6.add_edge(-8, -3)
    head6.add_edge(-8, 10)
    head6.filled = True
    head6.fill_color = "white"
    window.add(head6)
    # head7
    head7 = GPolygon()
    head7.add_vertex(point=(189, 184))
    head7.add_edge(3, -1)
    head7.add_edge(-3, -16)
    head7.add_edge(5, -8)
    head7.add_edge(3, -18)
    head7.add_edge(1, 17)
    head7.add_edge(-6, 10)
    head7.filled = True
    head7.fill_color = "white"
    window.add(head7)
    # head8
    head8 = GPolygon()
    head8.add_vertex(point=(190, 197))
    head8.add_edge(-9, 18)
    head8.add_edge(0, 4)
    head8.add_edge(-3, 0)
    head8.add_edge(0, -3)
    head8.add_edge(8, -18)
    head8.filled = True
    head8.fill_color = "white"
    window.add(head8)
    # head9
    head9 = GPolygon()
    head9.add_vertex(point=(170, 227))
    head9.add_edge(1, -5)
    head9.add_edge(5, -1)
    head9.add_edge(3, 5)
    head9.add_edge(-4, 3)
    head9.filled = True
    head9.fill_color = "white"
    window.add(head9)
    # head10
    head10 = GPolygon()
    head10.add_vertex(point=(172, 257))
    head10.add_edge(7, 10)
    head10.add_edge(-2, 5)
    head10.add_edge(6, 4)
    head10.add_edge(6, 0)
    head10.add_edge(17, 21)
    head10.add_edge(3, -3)
    head10.add_edge(-11, -18)
    head10.add_edge(-1, -15)
    head10.add_edge(3, -3)
    head10.add_edge(-2, -3)
    head10.add_edge(-12, -3)
    head10.add_edge(-3, 3)
    head10.add_edge(-2, -2)
    head10.add_edge(-6, 0)
    head10.filled = True
    head10.fill_color = "white"
    window.add(head10)
    # head11
    head11 = GPolygon()
    head11.add_vertex(point=(197, 262))
    head11.add_edge(1, 11)
    head11.add_edge(-4, -8)
    head11.filled = True
    head11.fill_color = "white"
    window.add(head11)
    # head12
    head12 = GPolygon()
    head12.add_vertex(point=(189, 234))
    head12.add_edge(-3, 3)
    head12.add_edge(6, 4)
    head12.add_edge(2, 8)
    head12.add_edge(3, -1)
    head12.add_edge(3, 7)
    head12.add_edge(0, -12)
    head12.add_edge(-3, -7)
    head12.add_edge(2, -2)
    head12.add_edge(-2, -5)
    head12.add_edge(-1, 4)
    head12.add_edge(-4, 2)
    head12.filled = True
    head12.fill_color = "white"
    window.add(head12)
    # head13
    head13 = GPolygon()
    head13.add_vertex(point=(165, 215))
    head13.add_edge(6, -10)
    head13.add_edge(7, -1)
    head13.add_edge(3, 3)
    head13.add_edge(-3, 5)
    head13.add_edge(0, 6)
    head13.add_edge(-6, 3)
    head13.add_edge(-1, -4)
    head13.filled = True
    head13.fill_color = "white"
    window.add(head13)
    # head14
    head14 = GPolygon()
    head14.add_vertex(point=(180, 221))
    head14.add_edge(3, 4)
    head14.add_edge(-2, 2)
    head14.add_edge(3, 7)
    head14.add_edge(6, -2)
    head14.add_edge(2, 1)
    head14.add_edge(3, -3)
    head14.add_edge(-1, -2)
    head14.filled = True
    head14.fill_color = "white"
    window.add(head14)
    # head15
    head15 = GPolygon()
    head15.add_vertex(point=(184, 243))
    head15.add_edge(9, 3)
    head15.add_edge(1, 7)
    head15.add_edge(-8, -1)
    head15.filled = True
    head15.fill_color = "white"
    window.add(head15)
    # head16
    head16 = GPolygon()
    head16.add_vertex(point=(220, 165))
    head16.add_edge(6, 8)
    head16.add_edge(0, 10)
    head16.add_edge(-2, 5)
    head16.add_edge(27, -2)
    head16.add_edge(1, -6)
    head16.add_edge(-3, -6)
    head16.add_edge(-6, -3)
    head16.add_edge(-9, -14)
    head16.filled = True
    head16.fill_color = "white"
    window.add(head16)
    # head17
    head17 = GPolygon()
    head17.add_vertex(point=(199, 156))
    head17.add_edge(6, 1)
    head17.add_edge(4, -7)
    head17.add_edge(-2, -7)
    head17.add_edge(-5, -1)
    head17.add_edge(2, 9)
    head17.filled = True
    head17.fill_color = "white"
    window.add(head17)
    # head18
    head18 = GPolygon()
    head18.add_vertex(point=(179, 220))
    head18.add_edge(14, 8)
    head18.add_edge(5, -2)
    head18.add_edge(9, -17)
    head18.add_edge(-11, 10)
    head18.add_edge(-3, 1)
    head18.add_edge(3, 5)
    head18.add_edge(-4, 1)
    head18.add_edge(-10, -6)
    head18.filled = True
    head18.fill_color = "white"
    window.add(head18)
    # head19
    head19 = GPolygon()
    head19.add_vertex(point=(201, 226))
    head19.add_edge(3, -3)
    head19.add_edge(6, 6)
    head19.add_edge(0, 4)
    head19.add_edge(-3, 10)
    head19.add_edge(-4, 5)
    head19.add_edge(-1, -6)
    head19.add_edge(-3, -7)
    head19.add_edge(2, -3)
    head19.filled = True
    head19.fill_color = "white"
    window.add(head19)
    # head20
    head20 = GPolygon()
    head20.add_vertex(point=(224, 189))
    head20.add_edge(1, -4)
    head20.add_edge(28, -2)
    head20.add_edge(-2, 4)
    head20.filled = True
    head20.fill_color = "white"
    window.add(head20)


def horn(window):
    # horn1
    horn1 = GPolygon()
    horn1.add_vertex(point=(39, 138))
    horn1.add_edge(10, -3)
    horn1.add_edge(78, 47)
    horn1.add_edge(1, 5)
    horn1.add_edge(-6, 13)
    horn1.filled = True
    horn1.fill_color = "white"
    window.add(horn1)
    # horn2
    horn2 = GPolygon()
    horn2.add_vertex(point=(123, 202))
    horn2.add_edge(7, -15)
    horn2.add_edge(0, -3)
    horn2.add_edge(6, 3)
    horn2.add_edge(-8, 20)
    horn2.filled = True
    horn2.fill_color = "white"
    window.add(horn2)
    # horn3
    horn3 = GPolygon()
    horn3.add_vertex(point=(131, 208))
    horn3.add_edge(6, -17)
    horn3.add_edge(4, 1)
    horn3.add_edge(5, -1)
    horn3.add_edge(3, 11)
    horn3.add_edge(-4, 8)
    horn3.add_edge(-3, -1)
    horn3.add_edge(-1, -5)
    horn3.add_edge(-6, 7)
    horn3.filled = True
    horn3.fill_color = "white"
    window.add(horn3)


def arm(window):
    # hand1
    hand1 = GPolygon()
    hand1.add_vertex(point=(226, 298))
    hand1.add_edge(8, 0)
    hand1.add_edge(4, -2)
    hand1.add_edge(7, 7)
    hand1.add_edge(4, 0)
    hand1.add_edge(10, 10)
    hand1.add_edge(4, -2)
    hand1.add_edge(2, 23)
    hand1.add_edge(-16, 7)
    hand1.add_edge(-5, 7)
    hand1.add_edge(-8, -6)
    hand1.add_edge(-5, 3)
    hand1.add_edge(-4, 0)
    hand1.add_edge(-5, -7)
    hand1.add_edge(2, -5)
    hand1.add_edge(-10, 3)
    hand1.add_edge(-6, -4)
    hand1.add_edge(-1, -6)
    hand1.add_edge(5, -5)
    hand1.add_edge(4, 1)
    hand1.add_edge(-1, 4)
    hand1.add_edge(8, -4)
    hand1.add_edge(-4, -1)
    hand1.add_edge(-8, -7)
    hand1.add_edge(-1, -4)
    hand1.add_edge(11, -3)
    hand1.add_edge(0, 4)
    hand1.add_edge(-3, 1)
    hand1.add_edge(5, 3)
    hand1.add_edge(5, -2)
    hand1.add_edge(6, 0)
    hand1.add_edge(4, -4)
    hand1.add_edge(-3, -5)
    hand1.add_edge(-6, 0)
    hand1.filled = True
    hand1.fill_color = "white"
    window.add(hand1)
    # hand2
    hand2 = GPolygon()
    hand2.add_vertex(point=(306, 287))
    hand2.add_edge(6, -2)
    hand2.add_edge(4, 4)
    hand2.add_edge(12, 1)
    hand2.add_edge(-4, 7)
    hand2.add_edge(4, 6)
    hand2.add_edge(-13, -1)
    hand2.add_edge(-8, -7)
    hand2.filled = True
    hand2.fill_color = "white"
    window.add(hand2)
    # hand3
    hand3 = GPolygon()
    hand3.add_vertex(point=(331, 291))
    hand3.add_edge(4, 0)
    hand3.add_edge(-1, 14)
    hand3.add_edge(-4, 0)
    hand3.add_edge(-4, -7)
    hand3.filled = True
    hand3.fill_color = "white"
    window.add(hand3)
    # hand4
    hand4 = GPolygon()
    hand4.add_vertex(point=(287, 340))
    hand4.add_edge(0, 6)
    hand4.add_edge(-8, 16)
    hand4.add_edge(14, 7)
    hand4.add_edge(0, -11)
    hand4.add_edge(7, -8)
    hand4.add_edge(-4, -2)
    hand4.add_edge(1, -10)
    hand4.filled = True
    hand4.fill_color = "white"
    window.add(hand4)
    # hand5
    hand5 = GPolygon()
    hand5.add_vertex(point=(302, 336))
    hand5.add_edge(0, 10)
    hand5.add_edge(4, -7)
    hand5.filled = True
    hand5.fill_color = "white"
    window.add(hand5)
    # arm1
    arm1 = GPolygon()
    arm1.add_vertex(point=(204, 41))
    arm1.add_edge(40, 80)
    arm1.add_edge(1, -6)
    arm1.add_edge(-27, -76)
    arm1.filled = True
    arm1.fill_color = "white"
    window.add(arm1)
    # arm2
    arm2 = GPolygon()
    arm2.add_vertex(point=(220, 39))
    arm2.add_edge(5, -1)
    arm2.add_edge(72, 83)
    arm2.add_edge(-3, 6)
    arm2.add_edge(22, 25)
    arm2.add_edge(-12, 4)
    arm2.add_edge(1, 26)
    arm2.add_edge(8, 11)
    arm2.add_edge(15, 11)
    arm2.add_edge(7, 21)
    arm2.add_edge(10, 6)
    arm2.add_edge(7, 23)
    arm2.add_edge(-3, 1)
    arm2.add_edge(-12, -11)
    arm2.add_edge(-2, 1)
    arm2.add_edge(-17, -20)
    arm2.add_edge(1, -9)
    arm2.add_edge(-15, -14)
    arm2.add_edge(-17, -1)
    arm2.add_edge(-14, -12)
    arm2.add_edge(-4, -2)
    arm2.add_edge(4, -9)
    arm2.add_edge(-29, -55)
    arm2.add_edge(3, -7)
    arm2.filled = True
    arm2.fill_color = "white"
    window.add(arm2)
    # arm3
    arm3 = GPolygon()
    arm3.add_vertex(point=(288, 203))
    arm3.add_edge(16, 2)
    arm3.add_edge(12, 10)
    arm3.add_edge(1, 10)
    arm3.add_edge(-9, 0)
    arm3.add_edge(-19, -8)
    arm3.filled = True
    arm3.fill_color = "white"
    window.add(arm3)
    # arm4
    arm4 = GPolygon()
    arm4.add_vertex(point=(259, 206))
    arm4.add_edge(-2, -6)
    arm4.add_edge(10, -11)
    arm4.add_edge(4, 0)
    arm4.add_edge(15, 13)
    arm4.add_edge(0, 15)
    arm4.add_edge(22, 10)
    arm4.add_edge(9, 0)
    arm4.add_edge(15, 18)
    arm4.add_edge(0, 3)
    arm4.add_edge(-8, 6)
    arm4.add_edge(-6, -1)
    arm4.add_edge(-3, -1)
    arm4.add_edge(0, -5)
    arm4.add_edge(-13, -18)
    arm4.add_edge(-16, -4)
    arm4.add_edge(-21, -23)
    arm4.add_edge(-3, 1)
    arm4.filled = True
    arm4.fill_color = "white"
    window.add(arm4)
    # arm5
    arm5 = GPolygon()
    arm5.add_vertex(point=(307, 157))
    arm5.add_edge(16, -4)
    arm5.add_edge(13, 6)
    arm5.add_edge(-8, 4)
    arm5.add_edge(0, 13)
    arm5.add_edge(4, 5)
    arm5.add_edge(12, 5)
    arm5.add_edge(10, -6)
    arm5.add_edge(0, -4)
    arm5.add_edge(2, 6)
    arm5.add_edge(13, 15)
    arm5.add_edge(-6, -2)
    arm5.add_edge(-11, 11)
    arm5.add_edge(-2, 25)
    arm5.add_edge(4, 10)
    arm5.add_edge(0, 7)
    arm5.add_edge(-8, -18)
    arm5.add_edge(-8, -6)
    arm5.add_edge(-9, -21)
    arm5.add_edge(-15, -13)
    arm5.add_edge(-7, -7)
    arm5.filled = True
    arm5.fill_color = "white"
    window.add(arm5)
    # arm6
    arm6 = GPolygon()
    arm6.add_vertex(point=(329, 164))
    arm6.add_edge(2, 11)
    arm6.add_edge(4, 5)
    arm6.add_edge(9, 1)
    arm6.add_edge(8, -2)
    arm6.add_edge(0, -8)
    arm6.add_edge(-2, -1)
    arm6.add_edge(1, 6)
    arm6.add_edge(-5, 3)
    arm6.add_edge(-11, -5)
    arm6.add_edge(-1, -7)
    arm6.add_edge(5, -3)
    arm6.add_edge(7, 3)
    arm6.add_edge(-7, -7)
    arm6.filled = True
    arm6.fill_color = "white"
    window.add(arm6)
    # arm7
    arm7 = GPolygon()
    arm7.add_vertex(point=(367, 199))
    arm7.add_edge(4, 2)
    arm7.add_edge(-1, 4)
    arm7.add_edge(3, 1)
    arm7.add_edge(-2, 6)
    arm7.add_edge(-9, 25)
    arm7.add_edge(1, 15)
    arm7.add_edge(-5, -4)
    arm7.add_edge(-2, -11)
    arm7.add_edge(-5, -5)
    arm7.add_edge(0, -21)
    arm7.filled = True
    arm7.fill_color = "white"
    window.add(arm7)
    # arm8
    arm8 = GPolygon()
    arm8.add_vertex(point=(260, 209))
    arm8.add_edge(2, -3)
    arm8.add_edge(4, 0)
    arm8.add_edge(18, 22)
    arm8.add_edge(14, 3)
    arm8.add_edge(15, 15)
    arm8.add_edge(1, 5)
    arm8.add_edge(-16, -14)
    arm8.add_edge(-14, -4)
    arm8.filled = True
    arm8.fill_color = "white"
    window.add(arm8)
    # arm9
    arm9 = GPolygon()
    arm9.add_vertex(point=(374, 203))
    arm9.add_edge(3, 0)
    arm9.add_edge(14, 13)
    arm9.add_edge(7, 1)
    arm9.add_edge(4, 5)
    arm9.add_edge(-7, 4)
    arm9.add_edge(-8, 13)
    arm9.add_edge(-2, 19)
    arm9.add_edge(6, 12)
    arm9.add_edge(-26, -15)
    arm9.add_edge(-1, -19)
    arm9.add_edge(10, -23)
    arm9.filled = True
    arm9.fill_color = "white"
    window.add(arm9)
    # arm10
    arm10 = GPolygon()
    arm10.add_vertex(point=(403, 224))
    arm10.add_edge(13, 11)
    arm10.add_edge(4, 1)
    arm10.add_edge(11, 6)
    arm10.add_edge(3, 4)
    arm10.add_edge(-16, -3)
    arm10.add_edge(-14, 5)
    arm10.add_edge(-10, 16)
    arm10.add_edge(-1, -10)
    arm10.add_edge(-4, 3)
    arm10.add_edge(1, -19)
    arm10.filled = True
    arm10.fill_color = "white"
    window.add(arm10)
    # arm11
    arm11 = GPolygon()
    arm11.add_vertex(point=(433, 250))
    arm11.add_edge(-14, 25)
    arm11.add_edge(2, 16)
    arm11.add_edge(-13, 22)
    arm11.add_edge(-16, 16)
    arm11.add_edge(-2, -2)
    arm11.add_edge(4, -14)
    arm11.add_edge(-1, -8)
    arm11.add_edge(-5, -8)
    arm11.add_edge(6, -30)
    arm11.add_edge(12, -16)
    arm11.add_edge(16, -6)
    arm11.filled = True
    arm11.fill_color = "white"
    window.add(arm11)
    # arm12
    arm12 = GPolygon()
    arm12.add_vertex(point=(433, 251))
    arm12.add_edge(4, 4)
    arm12.add_edge(-1, 16)
    arm12.add_edge(-11, 27)
    arm12.add_edge(-14, 22)
    arm12.add_edge(-17, 17)
    arm12.add_edge(-2, -4)
    arm12.add_edge(15, -18)
    arm12.add_edge(15, -23)
    arm12.add_edge(-1, -16)
    arm12.filled = True
    arm12.fill_color = "white"
    window.add(arm12)
    # arm13
    arm13 = GPolygon()
    arm13.add_vertex(point=(384, 303))
    arm13.add_edge(5, 0)
    arm13.add_edge(4, 5)
    arm13.add_edge(-3, 10)
    arm13.add_edge(-3, 8)
    arm13.add_edge(6, 12)
    arm13.add_edge(-7, 2)
    arm13.add_edge(2, -4)
    arm13.add_edge(-13, -14)
    arm13.filled = True
    arm13.fill_color = "white"
    window.add(arm13)
    # arm14
    arm14 = GPolygon()
    arm14.add_vertex(point=(381, 302))
    arm14.add_edge(-7, 17)
    arm14.add_edge(-5, -5)
    arm14.add_edge(-2, 17)
    arm14.add_edge(-7, 0)
    arm14.add_edge(3, -24)
    arm14.add_edge(-8, -10)
    arm14.add_edge(9, 5)
    arm14.filled = True
    arm14.fill_color = "white"
    window.add(arm14)
    # arm15
    arm15 = GPolygon()
    arm15.add_vertex(point=(326, 342))
    arm15.add_edge(5, -4)
    arm15.add_edge(0, 8)
    arm15.add_edge(12, -5)
    arm15.add_edge(-7, 6)
    arm15.add_edge(-4, 21)
    arm15.add_edge(2, 3)
    arm15.add_edge(-19, 6)
    arm15.filled = True
    arm15.fill_color = "white"
    window.add(arm15)
    # arm16
    arm16 = GPolygon()
    arm16.add_vertex(point=(359, 333))
    arm16.add_edge(6, 0)
    arm16.add_edge(-4, 25)
    arm16.add_edge(-6, 2)
    arm16.filled = True
    arm16.fill_color = "white"
    window.add(arm16)
    # arm17
    arm17 = GPolygon()
    arm17.add_vertex(point=(422, 234))
    arm17.add_edge(11, 6)
    arm17.add_edge(-2, -41)
    arm17.add_edge(-6, -28)
    arm17.add_edge(-4, -4)
    arm17.add_edge(-1, -6)
    arm17.add_edge(-6, -18)
    arm17.add_edge(-6, -5)
    arm17.add_edge(1, 6)
    arm17.add_edge(8, 15)
    arm17.add_edge(1, 16)
    arm17.add_edge(-2, 6)
    arm17.add_edge(5, 27)
    arm17.filled = True
    arm17.fill_color = "white"
    window.add(arm17)
    # arm18
    arm18 = GPolygon()
    arm18.add_vertex(point=(297, 129))
    arm18.add_edge(4, -9)
    arm18.add_edge(35, 36)
    arm18.add_edge(-14, -6)
    arm18.add_edge(-5, 0)
    arm18.filled = True
    arm18.fill_color = "white"
    window.add(arm18)
    # arm19
    arm19 = GPolygon()
    arm19.add_vertex(point=(228, 40))
    arm19.add_edge(69, 78)
    arm19.add_edge(1, -1)
    arm19.add_edge(-64, -72)
    arm19.filled = True
    arm19.fill_color = "white"
    window.add(arm19)


def body(window):
    # body1
    body1 = GPolygon()
    body1.add_vertex(point=(213, 209))
    body1.add_edge(2, -8)
    body1.add_edge(4, -3)
    body1.add_edge(20, 21)
    body1.add_edge(0, 12)
    body1.add_edge(16, 14)
    body1.add_edge(0, 15)
    body1.add_edge(-4, 10)
    body1.add_edge(-10, -27)
    body1.add_edge(-15, -2)
    body1.add_edge(-3, -7)
    body1.add_edge(-11, -2)
    body1.add_edge(0, -5)
    body1.add_edge(6, -8)
    body1.filled = True
    body1.fill_color = "white"
    window.add(body1)
    # body2
    body2 = GPolygon()
    body2.add_vertex(point=(222, 197))
    body2.add_edge(0, -6)
    body2.add_edge(18, 1)
    body2.add_edge(19, 32)
    body2.add_edge(-3, 6)
    body2.add_edge(4, 25)
    body2.add_edge(-3, 4)
    body2.add_edge(-2, -19)
    body2.add_edge(-12, -10)
    body2.add_edge(-2, -11)
    body2.filled = True
    body2.fill_color = "white"
    window.add(body2)
    # body3
    body3 = GPolygon()
    body3.add_vertex(point=(242, 193))
    body3.add_edge(5, 0)
    body3.add_edge(6, 6)
    body3.add_edge(3, 0)
    body3.add_edge(0, 7)
    body3.add_edge(24, 28)
    body3.add_edge(-20, -12)
    body3.add_edge(-9, -18)
    body3.filled = True
    body3.fill_color = "white"
    window.add(body3)
    # body4
    body4 = GPolygon()
    body4.add_vertex(point=(228, 150))
    body4.add_edge(8, -8)
    body4.add_edge(0, -5)
    body4.add_edge(14, -1)
    body4.add_edge(11, 21)
    body4.add_edge(-19, 10)
    body4.filled = True
    body4.fill_color = "white"
    window.add(body4)
    # body5
    body5 = GPolygon()
    body5.add_vertex(point=(243, 169))
    body5.add_edge(19, -9)
    body5.add_edge(9, 20)
    body5.add_edge(-2, 3)
    body5.add_edge(-8, 4)
    body5.add_edge(-3, 8)
    body5.add_edge(-6, -1)
    body5.add_edge(4, -9)
    body5.add_edge(-6, -12)
    body5.filled = True
    body5.fill_color = "white"
    window.add(body5)
    # body6
    body6 = GPolygon()
    body6.add_vertex(point=(317, 133))
    body6.add_edge(18, 21)
    body6.add_edge(15, 3)
    body6.add_edge(2, -2)
    body6.add_edge(3, 3)
    body6.add_edge(4, -11)
    body6.add_edge(0, -7)
    body6.add_edge(-24, -8)
    body6.filled = True
    body6.fill_color = "white"
    window.add(body6)
    # body7
    body7 = GPolygon()
    body7.add_vertex(point=(340, 158))
    body7.add_edge(16, 8)
    body7.add_edge(37, 27)
    body7.add_edge(-4, 12)
    body7.add_edge(4, 9)
    body7.add_edge(-3, 0)
    body7.add_edge(-14, -13)
    body7.add_edge(-4, 2)
    body7.add_edge(-1, -5)
    body7.add_edge(-14, -19)
    body7.add_edge(-6, -9)
    body7.filled = True
    body7.fill_color = "white"
    window.add(body7)
    # body8
    body8 = GPolygon()
    body8.add_vertex(point=(247, 275))
    body8.add_edge(3, 2)
    body8.add_edge(8, -9)
    body8.add_edge(5, 33)
    body8.add_edge(-12, -6)
    body8.add_edge(0, -3)
    body8.add_edge(-3, -3)
    body8.add_edge(0, -3)
    body8.filled = True
    body8.fill_color = "white"
    window.add(body8)
    # body9
    body9 = GPolygon()
    body9.add_vertex(point=(306, 247))
    body9.add_edge(9, 8)
    body9.add_edge(8, 3)
    body9.add_edge(7, -7)
    body9.add_edge(8, 9)
    body9.add_edge(-1, 26)
    body9.add_edge(-5, 0)
    body9.add_edge(-15, 0)
    body9.add_edge(-7, -3)
    body9.add_edge(-8, 1)
    body9.add_edge(1, 9)
    body9.add_edge(10, 10)
    body9.add_edge(-2, 3)
    body9.add_edge(-12, 3)
    body9.add_edge(-12, -1)
    body9.add_edge(0, -38)
    body9.filled = True
    body9.fill_color = "white"
    window.add(body9)
    # body10
    body10 = GPolygon()
    body10.add_vertex(point=(286, 248))
    body10.add_edge(8, -6)
    body10.add_edge(5, 0)
    body10.add_edge(3, 3)
    body10.add_edge(-16, 21)
    body10.filled = True
    body10.fill_color = "white"
    window.add(body10)
    # body11
    body11 = GPolygon()
    body11.add_vertex(point=(339, 261))
    body11.add_edge(12, 16)
    body11.add_edge(10, -7)
    body11.add_edge(-1, -6)
    body11.add_edge(-8, 1)
    body11.filled = True
    body11.fill_color = "white"
    window.add(body11)
    # body12
    body12 = GPolygon()
    body12.add_vertex(point=(353, 280))
    body12.add_edge(14, -10)
    body12.add_edge(8, -3)
    body12.add_edge(2, 4)
    body12.add_edge(5, -3)
    body12.add_edge(4, 2)
    body12.add_edge(-4, 19)
    body12.add_edge(-23, 8)
    body12.add_edge(-5, 0)
    body12.add_edge(1, -11)
    body12.filled = True
    body12.fill_color = "white"
    window.add(body12)
    # body13
    body13 = GPolygon()
    body13.add_vertex(point=(385, 285))
    body13.add_edge(4, 3)
    body13.add_edge(-2, 10)
    body13.add_edge(-21, 1)
    body13.add_edge(18, -10)
    body13.filled = True
    body13.fill_color = "white"
    window.add(body13)


def words(window):
    words_color = GColor(81, 66, 163)
    # word1
    word1 = GPolygon()
    word1.add_vertex(point=(14, 313))
    word1.add_edge(93, 25)
    word1.add_edge(7, 11)
    word1.add_edge(-15, 12)
    word1.add_edge(8, 21)
    word1.add_edge(23, 1)
    word1.add_edge(2, 5)
    word1.add_edge(-81, 23)
    word1.add_edge(17, -24)
    word1.add_edge(28, -4)
    word1.add_edge(-8, -20)
    word1.add_edge(6, -9)
    word1.add_edge(-4, -5)
    word1.add_edge(-12, 4)
    word1.add_edge(-20, -6)
    word1.add_edge(-6, -8)
    word1.add_edge(-25, -5)
    word1.filled = True
    word1.fill_color = words_color
    window.add(word1)
    # word2
    word2 = GPolygon()
    word2.add_vertex(point=(110, 315))
    word2.add_edge(8, 7)
    word2.add_edge(6, 1)
    word2.add_edge(6, 12)
    word2.add_edge(26, 5)
    word2.add_edge(-20, -27)
    word2.add_edge(-25, -72)
    word2.add_edge(28, 29)
    word2.add_edge(24, 70)
    word2.add_edge(11, 3)
    word2.add_edge(-2, -11)
    word2.add_edge(29, 31)
    word2.add_edge(-1, 15)
    word2.add_edge(41, 4)
    word2.add_edge(-15, 16)
    word2.add_edge(-5, 0)
    word2.add_edge(0, 21)
    word2.add_edge(-4, 3)
    word2.add_edge(-1, -27)
    word2.add_edge(5, 0)
    word2.add_edge(9, -9)
    word2.add_edge(-29, 0)
    word2.add_edge(0, 20)
    word2.add_edge(-5, 10)
    word2.add_edge(-20, -61)
    word2.add_edge(-40, -3)
    word2.add_edge(12, 31)
    word2.add_edge(-4, 9)
    word2.filled = True
    word2.fill_color = words_color
    window.add(word2)
    # word3
    word3 = GPolygon()
    word3.add_vertex(point=(166, 304))
    word3.add_edge(3, 16)
    word3.add_edge(30, 30)
    word3.add_edge(1, -6)
    word3.filled = True
    word3.fill_color = words_color
    window.add(word3)
    # word4
    word4 = GPolygon()
    word4.add_vertex(point=(175, 301))
    word4.add_edge(13, -1)
    word4.add_edge(13, 24)
    word4.add_edge(-3, 5)
    word4.filled = True
    word4.fill_color = words_color
    window.add(word4)
    # word5
    word5 = GPolygon()
    word5.add_vertex(point=(224, 354))
    word5.add_edge(25, 4)
    word5.add_edge(5, 7)
    word5.add_edge(-23, 0)
    word5.filled = True
    word5.fill_color = words_color
    window.add(word5)
    # word6
    word6 = GPolygon()
    word6.add_vertex(point=(244, 396))
    word6.add_edge(42, -20)
    word6.add_edge(5, 3)
    word6.add_edge(-34, 25)
    word6.filled = True
    word6.fill_color = words_color
    window.add(word6)
    # word7
    word7 = GPolygon()
    word7.add_vertex(point=(261, 228))
    word7.add_edge(22, 12)
    word7.add_edge(-2, 81)
    word7.add_edge(47, 1)
    word7.add_edge(1, 12)
    word7.add_edge(-4, 0)
    word7.add_edge(-26, 78)
    word7.add_edge(-2, -52)
    word7.add_edge(13, -21)
    word7.add_edge(-5, -11)
    word7.add_edge(-4, 0)
    word7.add_edge(-1, 7)
    word7.add_edge(-17, -1)
    word7.add_edge(1, 12)
    word7.add_edge(-10, 16)
    word7.add_edge(-15, -126)
    word7.filled = True
    word7.fill_color = words_color
    window.add(word7)
    # word8
    word8 = GPolygon()
    word8.add_vertex(point=(340, 272))
    word8.add_edge(12, 14)
    word8.add_edge(-10, 53)
    word8.add_edge(-6, 3)
    word8.filled = True
    word8.fill_color = words_color
    window.add(word8)
    # word9
    word9 = GPolygon()
    word9.add_vertex(point=(355, 302))
    word9.add_edge(5, 7)
    word9.add_edge(-8, 53)
    word9.add_edge(-11, 13)
    word9.add_edge(-5, -6)
    word9.add_edge(2, -19)
    word9.add_edge(9, -6)
    word9.filled = True
    word9.fill_color = words_color
    window.add(word9)
    # word10
    word10 = GPolygon()
    word10.add_vertex(point=(372, 323))
    word10.add_edge(12, 14)
    word10.add_edge(-9, 38)
    word10.add_edge(-44, 59)
    word10.add_edge(-8, 0)
    word10.add_edge(38, -65)
    word10.filled = True
    word10.fill_color = words_color
    window.add(word10)
    # word11
    word11 = GPolygon()
    word11.add_vertex(point=(392, 354))
    word11.add_edge(26, -1)
    word11.add_edge(12, -11)
    word11.add_edge(30, -78)
    word11.add_edge(28, -20)
    word11.add_edge(5, 2)
    word11.add_edge(-45, 96)
    word11.add_edge(-17, 13)
    word11.add_edge(7, 3)
    word11.add_edge(5, -4)
    word11.add_edge(24, 1)
    word11.add_edge(-6, 7)
    word11.add_edge(-32, 10)
    word11.add_edge(2, 8)
    word11.add_edge(-14, 12)
    word11.add_edge(-8, 16)
    word11.add_edge(-14, 13)
    word11.add_edge(21, -48)
    word11.add_edge(-14, -3)
    word11.add_edge(-3, 14)
    word11.add_edge(-11, 3)
    word11.add_edge(2, 8)
    word11.add_edge(-30, 23)
    word11.add_edge(-9, 0)
    word11.add_edge(37, -41)
    word11.filled = True
    word11.fill_color = words_color
    window.add(word11)
    # word12
    word12 = GPolygon()
    word12.add_vertex(point=(459, 340))
    word12.add_edge(9, -16)
    word12.add_edge(18, 4)
    word12.add_edge(4, 7)
    word12.filled = True
    word12.fill_color = words_color
    window.add(word12)
    # word13
    word13 = GPolygon()
    word13.add_vertex(point=(461, 375))
    word13.add_edge(74, -36)
    word13.add_edge(9, 0)
    word13.add_edge(-78, 41)
    word13.filled = True
    word13.fill_color = words_color
    window.add(word13)


if __name__ == '__main__':
    main()
